version: "2"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - misspell
    - gocyclo
    - goconst
    - gofmt
    - goimports

run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0