version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - misspell
    - gocyclo
    - goconst
    - gofmt
    - goimports
    - revive
    - gocritic
    - unconvert
    - unparam
    - whitespace
    - godot

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
